Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "containerd" do |containerd|
    containerd.vm.hostname = "containerd"
    containerd.vm.provider :virtualbox do |vb|
      vb.name = "containerd-centos"
    end
  end
end
